;;; phps-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from phps-mode.el

(autoload 'phps-mode-rescan-buffer "phps-mode" "\
Re-scan buffer." t)
(autoload 'phps-mode-flycheck-setup "phps-mode" "\
Setup `flycheck' for `phps-mode'.")
(autoload 'phps-mode-format-buffer "phps-mode" "\
Format current buffer according to PHPs mode." t)
(register-definition-prefixes "phps-mode" '("phps-mode"))


;;; Generated autoloads from phps-mode-ast.el

(register-definition-prefixes "phps-mode-ast" '("phps-mode-ast--"))


;;; Generated autoloads from phps-mode-automation-grammar.el

(register-definition-prefixes "phps-mode-automation-grammar" '("phps-mode-"))


;;; Generated autoloads from phps-mode-automation-parser-generator.el

(register-definition-prefixes "phps-mode-automation-parser-generator" '("phps-mode-automation-parser-generator--"))


;;; Generated autoloads from phps-mode-cache.el

(register-definition-prefixes "phps-mode-cache" '("phps-mode-cache-"))


;;; Generated autoloads from phps-mode-flymake.el

(register-definition-prefixes "phps-mode-flymake" '("phps-mode-flymake-init"))


;;; Generated autoloads from phps-mode-indent.el

(register-definition-prefixes "phps-mode-indent" '("phps-mode-indent-"))


;;; Generated autoloads from phps-mode-lex-analyzer.el

(register-definition-prefixes "phps-mode-lex-analyzer" '("phps-mode-lex-analyzer--"))


;;; Generated autoloads from phps-mode-lexer.el

(register-definition-prefixes "phps-mode-lexer" '("phps-"))


;;; Generated autoloads from phps-mode-lexer-generator.el

(register-definition-prefixes "phps-mode-lexer-generator" '("phps-mode-lexer-"))


;;; Generated autoloads from phps-mode-macros.el

(register-definition-prefixes "phps-mode-macros" '("phps-mode-"))


;;; Generated autoloads from phps-mode-parser.el

(register-definition-prefixes "phps-mode-parser" '("phps-"))


;;; Generated autoloads from phps-mode-parser-sdt.el

(register-definition-prefixes "phps-mode-parser-sdt" '("phps-mode-parser-sdt-"))


;;; Generated autoloads from phps-mode-serial.el

(register-definition-prefixes "phps-mode-serial" '("phps-mode-serial-"))


;;; Generated autoloads from phps-mode-syntax-color.el

(register-definition-prefixes "phps-mode-syntax-color" '("phps-mode-syntax-color--token-fo"))


;;; Generated autoloads from phps-mode-syntax-color-generator.el

(register-definition-prefixes "phps-mode-syntax-color-generator" '("phps-mode-syntax-color-generator--"))


;;; Generated autoloads from phps-mode-syntax-table.el

(register-definition-prefixes "phps-mode-syntax-table" '("phps-mode-syntax-table"))


;;; Generated autoloads from phps-mode-test.el

(register-definition-prefixes "phps-mode-test" '("phps-mode-test--"))

;;; End of scraped data

(provide 'phps-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; phps-mode-autoloads.el ends here
